name: wolfphotography
favicon: null
layout_spectrum: 0.7282354512717575
typography_spectrum: 0.06719949771650136
title: Wolf Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C8D0'
    - '#105080'
    - '#685838'
    - '#3888C0'
    - '#000000'
  brandStrength: 0.0625
  lightness: 0.23620821392110125
  saturation: 0.649106621031136
  rhythmicContrast: 0.39637192198399407
purpose:
  - name: null
    item: null
    url: null
